{
    "name": "Project Forecast Lines",
    "summary": "Project Forecast Lines",
    "version": "19.0.1.0.0",
    "author": "Camptocamp, Odoo Community Association (OCA)",
    "license": "AGPL-3",
    "category": "Project",
    "website": "https://github.com/OCA/project",
    "depends": [
        "hr",
        "hr_holidays",
        "product",
        "project",
        "sale",
        "sale_project",
        "sale_timesheet",
    ],
    "data": [
        "security/forecast_line_security.xml",
        "security/ir.model.access.csv",
        "views/sale_order_views.xml",
        "views/hr_employee_views.xml",
        "views/forecast_line_views.xml",
        "views/forecast_role_views.xml",
        "views/product_views.xml",
        "views/project_task_views.xml",
        "views/project_project_stage_views.xml",
        "views/res_config_settings_views.xml",
        "data/ir_cron.xml",
        "data/project_data.xml",
    ],
    "demo": [],
    "installable": True,
    "development_status": "Alpha",
    "application": True,
}
